/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_ZSTD_WIN
#define _Included_ZSTD_WIN
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_mitake_util_ZstdWin_print
(JNIEnv *env, jobject thiz);

JNIEXPORT jboolean JNICALL Java_com_mitake_util_ZstdWin_init
(JNIEnv *env, jobject thiz);

JNIEXPORT void JNICALL Java_com_mitake_util_ZstdWin_fini
(JNIEnv *env, jobject thiz);

JNIEXPORT jbyteArray JNICALL Java_com_mitake_util_ZstdWin_compress
(JNIEnv *env, jobject thiz, jbyteArray ary);

JNIEXPORT jbyteArray JNICALL Java_com_mitake_util_ZstdWin_decompress
(JNIEnv *env, jobject thiz, jbyteArray ary);

JNIEXPORT void JNICALL Java_com_mitake_util_ZstdWin_Native
(JNIEnv* env, jobject thiz);

#ifdef __cplusplus
}
#endif
#endif
